#!/bin/bash
# .githooks/sample-commit-msg

MESSAGE_FILE=$1

# Safely pass large diff via stdin, and message via file
git diff --cached | snelda execute \
  --config .snelda/commit-verify.json \
  --var-file message="$MESSAGE_FILE" \
  --var-stdin diff
